# API Configuration
api:
  mistral_model: "mistral-small-latest"

# File Paths
paths:
  logs_dir: "logs"
  log_file: "ai_category.log"
  data_dir: "data"
  optimized_titles_file: "optimized_titles.json"

# Articles Source
articles:
  source_url: "https://raw.githubusercontent.com/ahmedahmedovv/rss-fetch-and-translate/refs/heads/main/data/translated_feeds.json"
  limit: 10  # Limit for demo purposes

# Optimization Settings
optimization:
  max_retries: 3
  retry_delay: 5  # increased from 2 to 5 seconds
  request_delay: 2  # increased from 1 to 2 seconds between requests
  exponential_backoff: true  # new setting for exponential backoff
  max_backoff: 30  # maximum backoff time in seconds

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# AI Configuration
ai:
  prompt_template: |
    Task: Analyze the following article content and determine the most appropriate category.

    Article Title: "{title}"
    Optimized Title: "{optimized_title}"
    Article Description: "{description}"

    Requirements:
    1. Choose ONE primary category from the following list:
       - Technology
       - Business
       - Politics
       - Science
       - Health
       - Entertainment
       - Sports
       - Education
       - Environment
       - World News
    
    2. Base your decision on:
       - Main topic of the article
       - Key themes in both titles
       - Context from description
       - Target audience
    
    Important: Provide only the category name in your response, without any additional text or explanations.

  category_criteria:
    primary_categories:
      - Technology
      - Business
      - Politics
      - Science
      - Health
      - Entertainment
      - Sports
      - Education
      - Environment
      - World News
