# AI Configuration
ai:
  category_criteria:
    categories:
      - "politics"
      - "business"
      - "military"
      - "defense_policy"
      - "armed_forces"
      - "naval_operations"
      - "air_force"
      - "cyber_security"
      - "national_security"
      - "intelligence"
      - "defense_technology"
      - "military_strategy"
      - "veterans_affairs"
      - "weapons_systems"
      - "military_training"
      - "counter_terrorism"
      - "border_security"
      - "technology"
      - "science"
      - "health"
      - "education"
      - "environment"
      - "sports"
      - "entertainment"
      - "culture"
      - "economy"
      - "social_issues"
      - "international_relations"
      - "law_and_justice"
      - "innovation"
      - "media"
      - "polish_politics"
      - "polish_culture"
      - "polish_economy"
      - "polish_society"
      - "polish_history"
      - "polish_military"
      - "polish_education"
      - "polish_technology"
      - "polish_innovation"
      - "poland_eu_relations"
      - "polish_diaspora"
      - "polish_business"
      - "polish_defense"
      - "poland_nato_relations"
      - "polish_infrastructure"
      - "polish_military_modernization"
      - "polish_defense_industry"
      - "polish_army"
      - "polish_air_defense"
      - "polish_naval_forces"
      - "polish_special_forces"
      - "polish_territorial_defense"
      - "polish_military_procurement"
      - "polish_military_exercises"
      - "polish_military_partnerships"
      - "polish_defense_budget"
      - "polish_military_intelligence"
      - "polish_military_logistics"
      - "polish_military_research"
      - "polish_military_education"
      - "polish_military_reserves"
      - "polish_military_infrastructure"
      - "polish_military_history"
      - "polish_military_operations"
      - "polish_military_personnel"
      # Add more categories as needed
