# AI Configuration
ai:
  category_criteria:
    categories:
      - "Politics"
      - "Business"
      - "Military"
      - "Defense Policy"
      - "Armed Forces"
      - "Naval Operations"
      - "Air Force"
      - "Cyber Security"
      - "National Security"
      - "Intelligence"
      - "Defense Technology"
      - "Military Strategy"
      - "Veterans Affairs"
      - "Weapons Systems"
      - "Military Training"
      - "Counter Terrorism"
      - "Border Security"
      - "Technology"
      - "Science"
      - "Health"
      - "Education"
      - "Environment"
      - "Sports"
      - "Entertainment"
      - "Culture"
      - "Economy"
      - "Social Issues"
      - "International Relations"
      - "Law and Justice"
      - "Innovation"
      - "Media"
      - "Polish Politics"
      - "Polish Culture"
      - "Polish Economy"
      - "Polish Society"
      - "Polish History"
      - "Polish Military"
      - "Polish Education"
      - "Polish Technology"
      - "Polish Innovation"
      - "Poland EU Relations"
      - "Polish Diaspora"
      - "Polish Business"
      - "Polish Defense"
      - "Poland NATO Relations"
      - "Polish Infrastructure"
      - "Polish Military Modernization"
      - "Polish Defense Industry"
      - "Polish Army"
      - "Polish Air Defense"
      - "Polish Naval Forces"
      - "Polish Special Forces"
      - "Polish Territorial Defense"
      - "Polish Military Procurement"
      - "Polish Military Exercises"
      - "Polish Military Partnerships"
      - "Polish Defense Budget"
      - "Polish Military Intelligence"
      - "Polish Military Logistics"
      - "Polish Military Research"
      - "Polish Military Education"
      - "Polish Military Reserves"
      - "Polish Military Infrastructure"
      - "Polish Military History"
      - "Polish Military Operations"
      - "Polish Military Personnel"
      # Add more categories as needed
