name: Article Categorizer

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  push:
    branches: [ main ]  # Triggers on commits to main branch
  workflow_dispatch:    # Enables manual trigger from GitHub UI

jobs:
  categorize:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create necessary directories
      run: |
        mkdir -p data
        mkdir -p logs
    
    - name: Create .env file
      run: |
        echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" > .env
    
    - name: Run article categorizer
      run: python ai_category.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/categorized_articles.json
        git commit -m "Update article categories" || exit 0
        git push 